version: '3'
services:
  postgres:
    image: postgres:15-alpine
    network_mode: host
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: drone-mg
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
